(defun read-and-show-input-events ()
  (interactive)
  (while (not (eq 'f5 (setq event (read-event "Press <f5> to exit"))))
    (if (eq ?a event)
	(message-box "You typed 'a'"))
    (if (and (listp event) (eq 'mouse-1 (car event)))
	(let* ((position (event-start event))
	       (x-y (posn-x-y position)))
	  (message-box (format "left-click at (%d, %d)" (car x-y) (cdr x-y)))))))
